# Generated by Django 4.1.5 on 2023-02-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='basic', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=64)),
                ('date_of_birth', models.DateField()),
                ('height', models.PositiveIntegerField()),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
