# Generated by Django 4.1.5 on 2023-03-01 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitteam', '0004_alter_basicinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to=''),
        ),
        migrations.CreateModel(
            name='ProgressPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('progress_pic', models.ImageField(upload_to='progress_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_pic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
