# Generated by Django 4.1.5 on 2023-03-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitteam', '0007_alter_progresspics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresspics',
            name='pic_direction',
            field=models.CharField(choices=[('Front', 'Front'), ('Side', 'Side'), ('Back', 'Back')], max_length=64, null=True),
        ),
    ]
